name = "thematipack-fabric"
author = "funalex"
version = "1.5.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bb9404a04c1c7f4e1469ce701a4b504e0918b224fcf827287aad87ad015c10f4"

[versions]
fabric = "0.18.4"
minecraft = "1.20.1"
