name = "thematipack-fabric"
author = "funalex"
version = "1.5.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0710ddea46cbd23891f6ff0388490e7416de6e00a5cae5baee51e8d26aabefff"

[versions]
fabric = "0.18.4"
minecraft = "1.20.1"
