name = "thematipack-fabric"
author = "funalex"
version = "1.5.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8a73474a30bf28918dc6989a6cd939456cce4c41eaed7c2b3fd7cb61172ce130"

[versions]
fabric = "0.18.4"
minecraft = "1.20.1"
