name = "thematipack-fabric"
author = "funalex"
version = "1.5.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "074c06653156d6a4f0bea99911fec61a7d66b2f87bd79b9905cf97beb84c48c2"

[versions]
fabric = "0.18.4"
minecraft = "1.20.1"
