name = "thematipack-fabric"
author = "funalex"
version = "1.5.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2a25d137bc39d4d0e0ea90f11d36d531e9d1b9f2304fbfbbb84a6936fc33cdc1"

[versions]
fabric = "0.18.4"
minecraft = "1.20.1"
